-- Data generated by hand to provide test cases for key scenarios:
--   1. Limit establishment window (lew) in-control,     control window (cw) in-control
--   2. Limit establishment window (lew) in-control,     control window (cw) out-of-control
--   3. Limit establishment window (lew) out-of-control, control window (cw) in-control
--   4. Limit establishment window (lew) out-of-control, control window (cw) out-of-control
--
-- In these scenarios we assume that the assignable causes of all the out-of-control signals in limit establishment can
-- be found, so we add entries to the excluded_samples table.

insert into spc.observed_systems (name)
values ('Test System');

insert into spc.instruments (observed_system_id, name, type)
values ((select id from spc.observed_systems where name = 'Test System'), 'lew-in-control:cw-in-control', 'variable')
     , ((select id from spc.observed_systems where name = 'Test System'), 'lew-in-control:cw-out-control', 'variable')
     , ((select id from spc.observed_systems where name = 'Test System'), 'lew-out-control:cw-in-control', 'variable')
     , ((select id from spc.observed_systems where name = 'Test System'), 'lew-out-control:cw-out-control', 'variable');

--   1. Limit establishment window (lew) in-control, control window (cw) in-control

select spc.bulk_insert_example_data_measurements(
               'lew-in-control:cw-in-control',
               'lew-in-control',
               '[2023-04-01 00:00:00,2023-04-02 00:00:00)',
               'limit_establishment',
               array [
                 array [1, 2, 3], array [1, 2, 3], array [1, 2, 3], array [1, 2, 3], array [1, 2, 3],
                 array [1, 2, 3], array [1, 2, 3], array [1, 2, 3], array [1, 2, 3], array [1, 2, 3],
                 array [1, 2, 3], array [1, 2, 3], array [1, 2, 3], array [1, 2, 3], array [1, 2, 3],
                 array [1, 2, 3], array [1, 2, 3], array [1, 2, 3], array [1, 2, 3], array [1, 2, 3],
                 array [1, 2, 3], array [1, 2, 3], array [1, 2, 3], array [1, 2, 3], array [1, 2, 3]
                 ]
         );

select spc.bulk_insert_example_data_measurements(
               'lew-in-control:cw-in-control',
               'cw-in-control',
               '[2023-04-02 00:00:00,2023-04-03 00:00:00)',
               'control',
               array [
                 array [1, 2, 3],
                 array [1, 2, 3],
                 array [1, 2, 3],
                 array [1, 2, 3],
                 array [1, 2, 3]
                 ]
         );

--   2. Limit establishment window (lew) in-control, control window (cw) out-of-control

select spc.bulk_insert_example_data_measurements(
               'lew-in-control:cw-out-control',
               'lew-in-control',
               '[2023-04-03 00:00:00,2023-04-04 00:00:00)',
               'limit_establishment',
               array [
                 array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7],
                 array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7],
                 array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7],
                 array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7],
                 array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7]
                 ]
         );

select spc.bulk_insert_example_data_measurements(
               'lew-in-control:cw-out-control',
               'cw-out-control',
               '[2023-04-05 00:00:00,2023-04-06 00:00:00)',
               'control',
               array [
                 array [93, 94, 95, 96, 97, 98, 99], -- Xbar out of control upper
                 array [-99, -98, -97, -96, -95, -94, -93], -- Xbar out of control lower
                 array [-7, 4, 4, 4, 4, 6, 7], -- Rbar out of control upper
                 array [4, 4, 4, 4, 4, 4, 4] -- Rbar out of control lower
                 ]
         );

--   3. Limit establishment window (lew) out-of-control, control window (cw) in-control

select spc.bulk_insert_example_data_measurements(
               'lew-out-control:cw-in-control',
               'lew-out-control',
               '[2023-04-06 00:00:00,2023-04-07 00:00:00)',
               'limit_establishment',
               array [
                 array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7],
                 array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7],
                 array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7],
                 array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7],
                 array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7],
                 array [93, 94, 95, 96, 97, 98, 99], -- Xbar out of control upper
                 array [-99, -98, -97, -96, -95, -94, -93], -- Xbar out of control lower
                 array [-7, 4, 4, 4, 4, 6, 7], -- Rbar out of control upper
                 array [4, 4, 4, 4, 4, 4, 4] -- Rbar out of control lower
                 ]
         );

select spc.bulk_insert_example_data_measurements(
               'lew-out-control:cw-in-control',
               'cw-in-control',
               '[2023-04-07 00:00:00,2023-04-08 00:00:00)',
               'control',
               array [
                 array [1, 2, 3, 4, 5, 6, 7],
                 array [1, 2, 3, 4, 5, 6, 7],
                 array [1, 2, 3, 4, 5, 6, 7],
                 array [1, 2, 3, 4, 5, 6, 7],
                 array [1, 2, 3, 4, 5, 6, 7]
                 ]
         );
--   4. Limit establishment window (lew) out-of-control, control window (cw) out-of-control

select spc.bulk_insert_example_data_measurements(
               'lew-out-control:cw-out-control',
               'lew-out-control',
               '[2023-04-08 00:00:00,2023-04-09 00:00:00)',
               'limit_establishment',
               array [
                 array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7],
                 array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7],
                 array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7],
                 array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7],
                 array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7],
                 array [93, 94, 95, 96, 97, 98, 99], -- Xbar out of control upper
                 array [-99, -98, -97, -96, -95, -94, -93], -- Xbar out of control lower
                 array [-7, 4, 4, 4, 4, 6, 7], -- Rbar out of control upper
                 array [4, 4, 4, 4, 4, 4, 4] -- Rbar out of control lower
                 ]
         );

select spc.bulk_insert_example_data_measurements(
               'lew-out-control:cw-out-control',
               'cw-out-control',
               '[2023-04-09 00:00:00,2023-04-10 00:00:00)',
               'control',
               array [
                 array [93, 94, 95, 96, 97, 98, 99], -- Xbar out of control upper
                 array [-99, -98, -97, -96, -95, -94, -93], -- Xbar out of control lower
                 array [-7, 4, 4, 4, 4, 6, 7], -- Rbar out of control upper
                 array [4, 4, 4, 4, 4, 4, 4] -- Rbar out of control lower
                 ]
         );