-- Data generated by hand to provide test cases for key scenarios:
--   1. Limit establishment window (lew) in-control,     control window (cw) in-control
--   2. Limit establishment window (lew) in-control,     control window (cw) out-of-control
--   3. Limit establishment window (lew) out-of-control, control window (cw) in-control
--   4. Limit establishment window (lew) out-of-control, control window (cw) out-of-control
--   5. Limit establishment window (lew) out-of-control points excluded, control window (cw) in-control
--
-- In these scenarios we assume that the assignable causes of all the out-of-control signals in limit establishment can
-- be found, so we add entries to the excluded_samples table.

insert into spc_data.observed_systems (name)
values ('Test System');

-- @formatter:off
insert into spc_data.instruments (observed_system_id, name)
values ((select id from spc_data.observed_systems where name = 'Test System'), 'lew-in-control:cw-in-control')
     , ((select id from spc_data.observed_systems where name = 'Test System'), 'lew-in-control:cw-out-control')
     , ((select id from spc_data.observed_systems where name = 'Test System'), 'lew-out-control:cw-in-control')
     , ((select id from spc_data.observed_systems where name = 'Test System'), 'lew-out-control:cw-out-control')
     , ((select id from spc_data.observed_systems where name = 'Test System'), 'lew-out-control:cw-in-control:with-exclusions');
-- @formatter:on

--   1. Limit establishment window (lew) in-control, control window (cw) in-control

select spc_data.bulk_insert_example_data_measurements(
               'lew-in-control:cw-in-control',
               'lew-in-control',
               '[2023-04-01 00:00:00,2023-04-02 00:00:00)',
               'limit_establishment',
               array [
                 array [1, 2, 3], array [1, 2, 3], array [1, 2, 3], array [1, 2, 3], array [1, 2, 3],
                 array [1, 2, 3], array [1, 2, 3], array [1, 2, 3], array [1, 2, 3], array [1, 2, 3],
                 array [1, 2, 3], array [1, 2, 3], array [1, 2, 3], array [1, 2, 3], array [1, 2, 3],
                 array [1, 2, 3], array [1, 2, 3], array [1, 2, 3], array [1, 2, 3], array [1, 2, 3],
                 array [1, 2, 3], array [1, 2, 3], array [1, 2, 3], array [1, 2, 3], array [1, 2, 3]
                 ]
         );

select spc_data.bulk_insert_example_data_measurements(
               'lew-in-control:cw-in-control',
               'cw-in-control',
               '[2023-04-02 00:00:00,2023-04-03 00:00:00)',
               'control',
               array [
                 array [1, 2, 3],
                 array [1, 2, 3],
                 array [1, 2, 3],
                 array [1, 2, 3],
                 array [1, 2, 3]
                 ]
         );

--   2. Limit establishment window (lew) in-control, control window (cw) out-of-control

select spc_data.bulk_insert_example_data_measurements(
               'lew-in-control:cw-out-control',
               'lew-in-control',
               '[2023-04-03 00:00:00,2023-04-04 00:00:00)',
               'limit_establishment',
               array [
                 array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7],
                 array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7],
                 array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7],
                 array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7],
                 array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7]
                 ]
         );

select spc_data.bulk_insert_example_data_measurements(
               'lew-in-control:cw-out-control',
               'cw-out-control',
               '[2023-04-05 00:00:00,2023-04-06 00:00:00)',
               'control',
               array [
                 array [93, 94, 95, 96, 97, 98, 99], -- Xbar out of control upper
                 array [-99, -98, -97, -96, -95, -94, -93], -- Xbar out of control lower
                 array [-7, 4, 4, 4, 4, 6, 7], -- Rbar out of control upper
                 array [4, 4, 4, 4, 4, 4, 4] -- Rbar out of control lower
                 ]
         );

--   3. Limit establishment window (lew) out-of-control, control window (cw) in-control

select spc_data.bulk_insert_example_data_measurements(
               'lew-out-control:cw-in-control',
               'lew-out-control',
               '[2023-04-06 00:00:00,2023-04-07 00:00:00)',
               'limit_establishment',
               array [
                 array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7],
                 array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7],
                 array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7],
                 array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7],
                 array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7],
                 array [93, 94, 95, 96, 97, 98, 99], -- Xbar out of control upper
                 array [-99, -98, -97, -96, -95, -94, -93], -- Xbar out of control lower
                 array [-7, 4, 4, 4, 4, 6, 7], -- Rbar out of control upper
                 array [4, 4, 4, 4, 4, 4, 4] -- Rbar out of control lower
                 ]
         );

select spc_data.bulk_insert_example_data_measurements(
               'lew-out-control:cw-in-control',
               'cw-in-control',
               '[2023-04-07 00:00:00,2023-04-08 00:00:00)',
               'control',
               array [
                 array [1, 2, 3, 4, 5, 6, 7],
                 array [1, 2, 3, 4, 5, 6, 7],
                 array [1, 2, 3, 4, 5, 6, 7],
                 array [1, 2, 3, 4, 5, 6, 7],
                 array [1, 2, 3, 4, 5, 6, 7]
                 ]
         );
--   4. Limit establishment window (lew) out-of-control, control window (cw) out-of-control

select spc_data.bulk_insert_example_data_measurements(
               'lew-out-control:cw-out-control',
               'lew-out-control',
               '[2023-04-08 00:00:00,2023-04-09 00:00:00)',
               'limit_establishment',
               array [
                 array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7],
                 array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7],
                 array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7],
                 array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7],
                 array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7],
                 array [93, 94, 95, 96, 97, 98, 99], -- Xbar out of control upper
                 array [-99, -98, -97, -96, -95, -94, -93], -- Xbar out of control lower
                 array [-7, 4, 4, 4, 4, 6, 7], -- Rbar out of control upper
                 array [4, 4, 4, 4, 4, 4, 4] -- Rbar out of control lower
                 ]
         );

select spc_data.bulk_insert_example_data_measurements(
               'lew-out-control:cw-out-control',
               'cw-out-control',
               '[2023-04-09 00:00:00,2023-04-10 00:00:00)',
               'control',
               array [
                 array [93, 94, 95, 96, 97, 98, 99], -- Xbar out of control upper
                 array [-99, -98, -97, -96, -95, -94, -93], -- Xbar out of control lower
                 array [-7, 4, 4, 4, 4, 6, 7], -- Rbar out of control upper
                 array [4, 4, 4, 4, 4, 4, 4] -- Rbar out of control lower
                 ]
         );

--   5. Limit establishment window (lew) out-of-control points excluded, control window (cw) in-control

select spc_data.bulk_insert_example_data_measurements(
               'lew-out-control:cw-in-control:with-exclusions',
               'lew-out-control:with-exclusions',
               '[2023-04-10 00:00:00,2023-04-11 00:00:00)',
               'limit_establishment',
               array [
                 array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7],
                 array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7],
                 array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7],
                 array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7],
                 array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7], array [1, 2, 3, 4, 5, 6, 7],
                 array [93, 94, 95, 96, 97, 98, 99], -- Xbar out of control upper
                 array [-99, -98, -97, -96, -95, -94, -93], -- Xbar out of control lower
                 array [-7, 4, 4, 4, 4, 6, 7], -- Rbar out of control upper
                 array [4, 4, 4, 4, 4, 4, 4] -- Rbar out of control lower
                 ]
         );

update spc_data.samples
set include_in_limit_calculations = false
  , annotation                    = 'X bar example data exclusion'
where id in
      (select sample_id as reason_for_exclusion
       from spc_reports.x_bar_r_rules
       where control_status != 'in_control'
       order by lower(period) desc
       limit 2);

update spc_data.samples
set include_in_limit_calculations = false
  , annotation                    = 'R example data exclusion'
where id in
      (select sample_id as reason_for_exclusion
       from spc_reports.r_rules
       where control_status != 'in_control'
       order by lower(period) desc
       limit 2);

update spc_data.samples
set include_in_limit_calculations = false
  , annotation                    = 'X bar example data exclusion'
where id in
      (select sample_id as reason_for_exclusion
       from spc_reports.x_bar_s_rules
       where control_status != 'in_control'
       order by lower(period) desc
       limit 2);

update spc_data.samples
set include_in_limit_calculations = false
  , annotation                    = 'R example data exclusion'
where id in
      (select sample_id as reason_for_exclusion
       from spc_reports.s_rules
       where control_status != 'in_control'
       order by lower(period) desc
       limit 2);

select spc_data.bulk_insert_example_data_measurements(
               'lew-out-control:cw-in-control:with-exclusions',
               'cw-in-control:with-exclusions',
               '[2023-04-11 00:00:00,2023-04-12 00:00:00)',
               'control',
               array [
                 array [1, 2, 3],
                 array [1, 2, 3],
                 array [1, 2, 3],
                 array [1, 2, 3],
                 array [1, 2, 3]
                 ]
         );
